dataset_args:
  dataset_name: MNIST
  target_labels:
    - 0
    - 1
model_args:
  model_name: MLP
  in_features: 784
  out_classes: 2
  hidden_layers:
    - 200
    - 200
  loss_name: CrossEntropyLoss 
  # loss_args: {}
  optimizer_name: Adam
  optimizer_args:
    lr: 0.00005
    # weight_decay: 0.001