bash scripts/fedavg.sh configurations/learning/mnist_0_1.yaml
bash scripts/rfa_whole.sh configurations/learning/mnist_0_1.yaml
bash scripts/rfa_component.sh configurations/learning/mnist_0_1.yaml
bash scripts/clusteragg_agglo_average.sh configurations/learning/mnist_0_1.yaml
bash scripts/clusteragg_agglo_median.sh configurations/learning/mnist_0_1.yaml
bash scripts/clusteragg_kmeans_average_3.sh configurations/learning/mnist_0_1.yaml
bash scripts/clusteragg_kmeans_average_5.sh configurations/learning/mnist_0_1.yaml
bash scripts/clusteragg_kmeans_average_8.sh configurations/learning/mnist_0_1.yaml
bash scripts/clusteragg_kmeans_median_3.sh configurations/learning/mnist_0_1.yaml
bash scripts/clusteragg_kmeans_median_5.sh configurations/learning/mnist_0_1.yaml
bash scripts/clusteragg_kmeans_median_8.sh configurations/learning/mnist_0_1.yaml
bash scripts/random_sample_simple_0_7.sh configurations/learning/mnist_0_1.yaml
bash scripts/random_sample_simple_0_5.sh configurations/learning/mnist_0_1.yaml
bash scripts/random_sample_simple_0_3.sh configurations/learning/mnist_0_1.yaml
