output_dir: output/MNIST/MLP/ClusterAgg/median/yes_straggle
sim_epoch: 200
dataset_args:
  dataset_name: MNIST
  target_labels:
    - 0
    - 1
model_args:
  model_type: MLP
  in_features: 784
  out_classes: 10
  hidden_layers:
    - 200
    - 200
  loss_func: CrossEntropyLoss 
  # loss_args: {}
  optimizer_func: Adam
  optimizer_args:
    lr: 0.01
    weight_decay: 0.001
agg_args:
  agg_type: ClusterAgg
  agg_mode: median
client_args:
  poison_ratio: 1
  n_train_epoch: 1
scheduler_args:
  n_clients: 1000
  n_malicious_clients: .3
  n_clients_per_round: 20
  max_delay: 10
  n_delay_min: 0
  n_delay_max: 10
